language: python

python:
  - "3.6"
  - "3.7"

dist: xenial

sudo: false

env:
  - ES_VERSION=6.6.2 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz



# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - pip install -U tox-travis
script:
  - wget -q --waitretry=1 --retry-connrefused -T 45 -O - http://127.0.0.1:9200
  - tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    branch: master
    repo: oceanprotocol/aquarius
    python: 3.6

notifications:
   email: false
