name: Push documentation to docs repo

on:
  workflow_dispatch:
  push:
    branches:
      - push-to-docs

jobs:
  push-to-docs:
    uses: nevermined-io/reusable-workflows/.github/workflows/push-to-docs.yml@main
    with:
      path-to-push: external/metadata
    secrets: inherit